---
- name: Install Telegraf
  yum:
    name: "{{ telegraf_src }}"
    state: present

- name: Copy Telegraf configuration
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf

- name: Force Telegraf restart
  service:
    name: telegraf
    state: restarted
